# Generated by Django 5.0.7 on 2024-09-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano', models.CharField(max_length=255)),
                ('idioma', models.CharField(max_length=255)),
                ('classif', models.CharField(max_length=255)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
        ),
    ]
