# Generated by Django 5.0.7 on 2024-09-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='Imagem',
            new_name='imagem',
        ),
    ]
